# Transform Data

Goal of this notebook is to convert all race data into a flat-file of the following schema:

- RaceId 
- DriverId
- TeamId
- Position (Starting)
- Starting Tyre Compound
- Starting Tyre freshness (boolean)  

Pit stop 1   
- A column to measure time taken to first pit stop  
- Lap at which first pit stop occurred
- Time taken for first pit stop
- Compound after first pit stop
- Freshness of tyre after first pit stop  

Pit stop 2  
- A column to measure time taken to second pit stop
- Lap at which second pit stop occurred
- Time taken for second pit stop
- Compound after second pit stop
- Freshness of tyre after second pit stop 

Pit stop three
- A column to measure time taken to third pit stop (if it exists)
- Lap at which third pit stop occurred (if it exists)
- Time taken for third pit stop (if it exists)
- Compound after third pit stop (if it exists)
- Freshness of tyre after third pit stop (if it exists)

- Number of laps to change tires after rain begins
- Number of laps to change tires after rain ends
- Rainfall present on track
- Maximum duration of rainfall (if present)
- Maximum difference in weather temperature
- Gradient of weather temperature
- Safety car deployed (multiple columns storing the lap at which it occurred, maybe go up to 72)
- Pit stops during a safety car
- Matrix of [Angle, Distance] for given track

Target
- GridPosition (Finishing, this will be our target)

In [19]:
import fastf1
import numpy as np
from pathlib import Path
import pandas as pd
from IPython.display import display

DATA_PATH = Path.cwd().parent / "data"
fastf1.Cache.enable_cache(DATA_PATH)

In [3]:
race = fastf1.get_session(2021, "Imola", "R")
race.load()

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.2]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 33 completed the race distance 00:01.003000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['33', '44', '4', '16', '55', '3', '10', '18', '31', '14', '11', '22', '7', '99', '5', '47', '9', '77', '63', '6']

## Race Starting Grid and Results

In [3]:
race.results['Position'] # finishing

33     1.0
44     2.0
4      3.0
16     4.0
55     5.0
3      6.0
10     7.0
18     8.0
31     9.0
14    10.0
11    11.0
22    12.0
7     13.0
99    14.0
5     15.0
47    16.0
9     17.0
77    18.0
63    19.0
6     20.0
Name: Position, dtype: float64

In [4]:
race.results['GridPosition'] # starting

33     3.0
44     1.0
4      7.0
16     4.0
55    11.0
3      6.0
10     5.0
18    10.0
31     9.0
14    15.0
11     2.0
22    20.0
7     16.0
99    17.0
5      0.0
47    18.0
9     19.0
77     8.0
63    12.0
6     14.0
Name: GridPosition, dtype: float64

In [5]:
race.laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [6]:
race.laps[['Driver', 'DriverNumber', 'LapNumber', 'PitInTime', 'FreshTyre', 'TyreLife', 'Compound', 'TrackStatus']]

,Driver,DriverNumber,LapNumber,PitInTime,FreshTyre,TyreLife,Compound,TrackStatus
0,GAS,10,1.0,NaT,True,1.0,WET,124
1,GAS,10,2.0,NaT,True,2.0,WET,4
2,GAS,10,3.0,NaT,True,3.0,WET,4
3,GAS,10,4.0,NaT,True,4.0,WET,4
4,GAS,10,5.0,NaT,True,5.0,WET,4
...,...,...,...,...,...,...,...,...
1122,GIO,99,58.0,NaT,False,31.0,MEDIUM,1
1123,GIO,99,59.0,NaT,False,32.0,MEDIUM,1
1124,GIO,99,60.0,NaT,False,33.0,MEDIUM,1
1125,GIO,99,61.0,NaT,False,34.0,MEDIUM,12
1126,GIO,99,62.0,NaT,False,35.0,MEDIUM,1

## Weather

In [ ]:
weather_data = race.weather_data.copy(deep=True)
# weather_data.assign(rain_start=lambda x: (x.Rainfall.shift(-1) == False and  x.Rainfall == True ))

weather_data['rain_start'] = (weather_data['Rainfall'] == True) & (weather_data['Rainfall'].shift(1) == False)
weather_data['rain_stop'] = (weather_data['Rainfall'].shift(1) == True) & (weather_data['Rainfall'] == False)
weather_data['rain_start_time'] = weather_data['Time'].where(weather_data['rain_start']) 
weather_data['rain_stop_time'] = weather_data['Time'].where(weather_data['rain_stop'])

weather_data['rain_start_time'] = weather_data['rain_start_time'].dt.total_seconds().astype(float)
weather_data['rain_stop_time'] = weather_data['rain_stop_time'].dt.total_seconds().astype(float)

weather_data['rain_start_time'] = weather_data['rain_start_time'].ffill()
weather_data['rain_stop_time'] = weather_data['rain_stop_time'].ffill()

weather_data['Time'] = weather_data['Time'].dt.total_seconds().astype(float)


weather_data['max_temp'] = weather_data['TrackTemp'].max()
weather_data['min_temp'] = weather_data['TrackTemp'].min()
weather_data['avg_temp'] = weather_data['TrackTemp'].mean()
weather_data['std_temp'] = weather_data['TrackTemp'].std()



weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed,rain_start,rain_stop,rain_start_time,rain_stop_time,max_temp,min_temp,avg_temp,std_temp
0,41.291,9.8,68.7,1011.7,True,18.1,61,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
1,101.287,9.7,70.0,1011.6,True,18.1,261,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
2,161.294,9.6,69.2,1011.6,True,18.0,243,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
3,221.289,9.4,68.3,1011.6,True,17.7,250,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
4,281.288,9.3,67.9,1011.7,True,17.6,259,0.5,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
5,341.289,9.3,69.1,1011.6,True,17.6,256,0.5,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
6,401.296,9.3,69.4,1011.6,True,17.5,248,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
7,461.289,9.2,70.6,1011.6,True,17.5,268,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
8,521.293,9.2,70.5,1011.6,True,17.5,214,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
9,581.290,9.2,70.7,1011.7,True,17.5,237,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
10,641.290,9.2,71.8,1011.7,True,17.5,285,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
11,701.294,9.3,70.5,1011.6,True,17.6,260,0.5,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
12,761.305,9.2,71.9,1011.6,True,17.5,241,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
13,821.321,9.2,74.0,1011.7,True,17.4,241,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
14,881.319,9.2,73.8,1011.6,True,17.4,234,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
15,941.321,9.2,74.9,1011.7,True,17.4,260,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
16,1001.335,9.2,75.0,1011.6,True,17.4,258,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
17,1061.336,9.2,73.1,1011.5,True,17.5,270,0.6,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
18,1121.352,9.2,74.0,1011.5,True,17.5,244,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
19,1181.352,9.2,75.4,1011.5,True,17.4,266,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
20,1241.361,9.2,76.2,1011.5,True,17.4,272,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
21,1301.350,9.2,74.9,1011.5,True,17.4,271,0.5,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
22,1361.350,9.3,74.8,1011.5,True,17.5,259,0.5,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
23,1421.351,9.2,74.6,1011.5,True,17.4,271,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
24,1481.352,9.2,73.1,1011.5,True,17.3,273,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
25,1541.369,9.3,74.7,1011.5,True,17.5,244,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
26,1601.366,9.3,74.3,1011.5,True,17.5,281,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
27,1661.381,9.4,76.0,1011.5,True,17.5,248,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
28,1721.382,9.4,76.4,1011.5,True,17.7,258,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
29,1781.397,9.4,75.5,1011.5,True,17.8,273,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
30,1841.414,9.4,74.6,1011.5,True,17.8,0,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
31,1901.414,9.4,75.7,1011.5,True,17.7,177,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
32,1961.413,9.5,77.1,1011.5,True,17.7,0,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
33,2021.418,9.6,75.0,1011.5,True,17.7,178,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
34,2081.415,9.6,75.4,1011.5,True,17.3,203,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
35,2141.414,9.5,75.7,1011.5,True,17.2,199,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
36,2201.414,9.5,74.2,1011.4,True,17.1,226,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
37,2261.414,9.4,74.4,1011.5,True,16.9,122,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
38,2321.416,9.6,75.6,1011.6,True,16.7,206,0.5,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
39,2381.413,9.6,76.8,1011.5,True,16.5,91,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
40,2441.413,9.8,76.5,1011.5,True,16.5,218,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
41,2501.414,9.7,74.8,1011.5,True,16.4,238,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
42,2561.413,9.6,75.9,1011.5,True,16.4,197,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
43,2621.412,9.7,74.0,1011.5,True,16.4,268,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
44,2681.414,9.7,74.7,1011.5,True,16.3,95,0.2,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
45,2741.411,9.7,74.9,1011.4,True,16.2,288,0.4,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
46,2801.412,9.7,73.2,1011.5,True,16.2,359,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
47,2861.413,9.8,74.3,1011.5,True,16.2,77,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
48,2921.433,9.9,72.5,1011.4,True,16.2,0,0.1,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
49,2981.412,9.9,72.5,1011.5,True,16.2,85,0.6,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
50,3041.421,10.0,72.2,1011.4,True,16.2,83,0.3,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
51,3101.403,10.0,71.3,1011.5,True,16.1,99,0.7,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
52,3161.413,10.0,71.2,1011.3,True,15.7,97,0.7,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
53,3221.418,10.1,67.7,1011.4,True,15.2,81,0.8,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
54,3281.413,10.1,69.9,1011.4,True,15.2,99,0.8,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
55,3341.421,10.2,68.8,1011.3,True,15.0,87,0.6,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
56,3401.415,10.2,68.2,1011.4,True,14.9,91,0.9,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
57,3461.413,10.2,69.2,1011.4,True,14.6,89,0.9,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
58,3521.412,10.3,69.6,1011.5,True,14.5,90,0.7,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
59,3581.414,10.3,68.5,1011.3,True,14.3,82,0.8,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
60,3641.412,10.3,68.8,1011.3,True,14.3,103,0.8,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
61,3701.411,10.4,69.6,1011.3,True,14.1,93,0.7,False,False,NaN,NaN,18.6,13.8,16.827329,1.301921
62,3761.415,10.4,69.1,1011.3,False,14.0,75,0.8,False,True,NaN,3761.415,18.6,13.8,16.827329,1.301921
63,3821.411,10.4,69.3,1011.3,False,14.1,67,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
64,3881.423,10.4,67.7,1011.1,False,14.0,88,0.6,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
65,3941.413,10.4,68.8,1011.3,False,13.9,83,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
66,4001.414,10.4,68.9,1011.4,False,13.8,89,0.9,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
67,4061.412,10.5,67.7,1011.6,False,13.9,70,0.6,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
68,4121.412,10.4,67.3,1011.2,False,13.9,79,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
69,4181.414,10.5,68.6,1011.3,False,13.9,78,0.9,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
70,4241.412,10.6,66.5,1011.3,False,14.1,89,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
71,4301.412,10.6,68.1,1011.0,False,14.2,81,0.9,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
72,4361.412,10.7,68.9,1011.3,False,14.2,85,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
73,4421.412,10.7,68.7,1011.4,False,14.4,99,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
74,4481.412,10.8,69.2,1011.1,False,14.6,105,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
75,4541.409,10.9,68.6,1011.3,False,14.7,92,1.0,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
76,4601.429,10.9,67.7,1011.2,False,14.9,112,1.0,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
77,4661.416,11.0,67.7,1011.3,False,15.0,95,1.0,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
78,4721.412,11.1,67.6,1011.2,False,15.2,102,1.0,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
79,4781.413,11.1,67.3,1011.1,False,15.3,97,1.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
80,4841.419,11.1,65.9,1011.2,False,15.4,88,1.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
81,4901.415,11.1,65.0,1011.3,False,15.5,84,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
82,4961.413,11.1,66.0,1011.3,False,15.5,105,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
83,5021.413,11.0,66.1,1011.2,False,15.4,100,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
84,5081.415,11.1,66.0,1011.3,False,15.6,91,1.0,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
85,5141.418,11.1,65.9,1011.2,False,15.7,97,0.9,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
86,5201.413,11.2,66.0,1011.2,False,15.8,117,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
87,5261.411,11.1,66.5,1011.0,False,15.9,155,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
88,5321.411,11.2,67.1,1011.2,False,15.9,113,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
89,5381.413,11.2,67.3,1011.2,False,16.0,126,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
90,5441.412,11.1,67.1,1011.2,False,16.0,229,0.4,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
91,5501.413,11.0,66.8,1011.2,False,15.9,230,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
92,5561.416,11.0,68.2,1011.3,False,15.9,232,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
93,5621.414,11.1,69.6,1011.2,False,16.1,234,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
94,5681.412,11.1,70.1,1011.2,False,16.3,240,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
95,5741.412,11.0,69.6,1011.2,False,16.4,208,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
96,5801.412,11.0,70.4,1011.2,False,16.5,88,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
97,5861.414,11.0,68.9,1011.2,False,16.6,251,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
98,5921.412,11.0,69.7,1011.2,False,16.8,228,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
99,5981.416,11.0,68.3,1011.1,False,16.8,238,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
100,6041.419,10.9,69.9,1011.2,False,16.8,255,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
101,6101.412,10.9,71.1,1011.2,False,17.2,351,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
102,6161.412,11.1,71.3,1011.2,False,17.4,245,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
103,6221.421,11.1,70.7,1011.2,False,17.5,283,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
104,6281.413,11.1,70.5,1011.1,False,17.7,282,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
105,6341.419,11.1,68.9,1011.1,False,17.8,251,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
106,6401.411,11.0,69.8,1011.1,False,17.8,271,0.4,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
107,6461.416,10.9,70.6,1011.1,False,17.7,240,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
108,6521.416,10.9,70.8,1011.1,False,17.8,275,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
109,6581.417,11.0,71.0,1011.0,False,17.8,266,0.4,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
110,6641.427,11.0,70.9,1011.1,False,17.9,286,0.4,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
111,6701.414,11.0,71.9,1011.0,False,17.9,263,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
112,6761.411,11.1,71.8,1011.0,False,18.0,295,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
113,6821.413,11.1,71.3,1011.1,False,18.0,248,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
114,6881.412,11.2,71.4,1011.1,False,18.0,241,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
115,6941.418,11.3,70.1,1011.0,False,18.3,277,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
116,7001.412,11.3,68.3,1011.0,False,18.2,260,0.1,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
117,7061.404,11.3,69.2,1011.1,False,18.2,268,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
118,7121.414,11.2,68.9,1011.0,False,18.2,287,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
119,7181.415,11.2,69.1,1011.0,False,18.1,235,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
120,7241.413,11.3,69.8,1011.0,False,18.1,114,0.3,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
121,7301.412,11.5,69.4,1011.2,False,18.2,42,0.6,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
122,7361.413,11.6,67.9,1011.0,False,18.3,84,0.2,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
123,7421.413,11.6,67.3,1011.1,False,18.2,297,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
124,7481.415,11.5,67.1,1010.7,False,18.0,94,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
125,7541.413,11.5,66.9,1011.1,False,17.9,84,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
126,7601.415,11.6,66.2,1011.0,False,17.9,91,0.9,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
127,7661.415,11.6,66.7,1011.0,False,17.9,163,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
128,7721.402,11.6,67.0,1011.0,False,17.7,88,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
129,7781.414,11.6,67.1,1011.0,False,17.6,88,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
130,7841.413,11.6,66.9,1011.0,False,17.6,113,0.6,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
131,7901.412,11.6,66.6,1010.9,False,17.7,122,0.7,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
132,7961.412,11.6,66.2,1010.9,False,17.6,107,0.8,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
133,8021.420,11.7,66.6,1011.0,False,17.5,92,0.5,False,False,NaN,3761.415,18.6,13.8,16.827329,1.301921
134,8081.417,11.7,66.3,1011.1,True,17.6,70,0.7,True,False,8081.417,3761.415,18.6,13.8,16.827329,1.301921
135,8141.413,11.7,66.1,1010.9,True,17.8,80,0.5,False,False,8081.417,3761.415,18.6,13.8,16.827329,1.301921
136,8201.411,11.8,64.8,1011.0,True,17.8,108,0.6,False,False,8081.417,3761.415,18.6,13.8,16.827329,1.301921
137,8261.413,11.8,64.8,1011.4,True,17.8,97,0.5,False,False,8081.417,3761.415,18.6,13.8,16.827329,1.301921
138,8321.413,11.7,64.6,1011.0,False,17.8,92,0.5,False,True,8081.417,8321.413,18.6,13.8,16.827329,1.301921
139,8381.413,11.7,65.2,1011.1,False,17.8,113,0.7,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
140,8441.412,11.8,65.9,1011.0,False,17.7,96,0.7,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
141,8501.412,11.6,65.9,1010.7,False,17.6,80,0.9,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
142,8561.415,11.6,65.6,1011.0,False,17.6,83,0.6,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
143,8621.412,11.6,65.8,1011.0,False,17.7,114,0.6,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
144,8681.411,11.7,66.2,1010.9,False,17.7,118,0.5,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
145,8741.414,11.7,66.0,1010.9,False,17.7,82,0.3,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
146,8801.412,11.7,65.8,1010.9,False,17.7,98,0.5,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
147,8861.413,11.7,65.7,1010.9,False,17.8,87,0.8,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
148,8921.412,11.7,65.2,1010.9,False,17.6,35,0.3,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
149,8981.414,11.7,65.5,1010.9,False,17.7,62,0.6,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
150,9041.436,11.7,64.9,1010.9,False,17.8,320,0.3,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
151,9101.410,11.7,65.0,1011.0,False,17.8,62,0.3,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
152,9161.412,11.8,63.2,1010.9,False,17.7,92,0.3,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
153,9221.412,11.9,64.4,1010.9,False,17.7,107,0.9,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
154,9281.414,12.0,63.8,1011.0,False,17.8,105,0.8,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
155,9341.412,12.1,64.0,1010.8,False,17.9,91,0.8,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
156,9401.414,12.1,63.7,1010.8,False,18.0,80,0.7,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
157,9461.416,12.1,63.2,1010.9,False,18.5,100,0.7,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
158,9521.412,12.2,62.6,1011.0,False,18.5,89,0.6,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
159,9581.413,12.3,62.4,1011.0,False,18.5,90,0.7,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921
160,9641.411,12.3,61.6,1010.9,False,18.6,72,0.3,False,False,8081.417,8321.413,18.6,13.8,16.827329,1.301921

In [ ]:
corners = race.get_circuit_info().corners[['Angle', 'Distance']]
corners.values

array([[ -97.8239287 ,  348.84381074],
       [ 111.88313377,  967.34205354],
       [ -30.15716703, 1029.34771621],
       [ 140.59195787, 1169.99862496],
       [-178.31172885, 1602.72018903],
       [ -21.43865197, 1704.16521124],
       [-171.05139602, 1987.36188568],
       [  90.97300951, 2396.17181181],
       [ -41.14815521, 2644.74609896],
       [-180.56795043, 2770.2173105 ],
       [-191.14447209, 3034.04691098],
       [ 115.09022179, 3133.4751165 ],
       [ -90.97901268, 3206.81813543],
       [  64.02888553, 3632.2803438 ],
       [ -96.25082234, 3674.66006957],
       [ -51.56989886, 4229.65969617],
       [  -7.57990847, 4425.27764484],
       [  86.24746694, 4566.39225556],
       [ -73.50537254, 4872.57949364]])

## Race Starting/Ending Positions

In [12]:
start_end_positions = pd.concat([race.results['Position'],race.results['GridPosition']], axis=1).rename(columns={'Position': 'target', 'GridPosition': 'starting_position'}).astype({'starting_position': 'int', 'target': 'int'})
start_end_positions

    target  starting_position
33       1                  3
44       2                  1
4        3                  7
16       4                  4
55       5                 11
3        6                  6
10       7                  5
18       8                 10
31       9                  9
14      10                 15
11      11                  2
22      12                 20
7       13                 16
99      14                 17
5       15                  0
47      16                 18
9       17                 19
77      18                  8
63      19                 12
6       20                 14

In [13]:
laps = race.laps[['Driver', 'DriverNumber', 'LapNumber', 'PitInTime', 'PitOutTime', 'FreshTyre', 'TyreLife', 'Compound', 'TrackStatus']]

In [14]:
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)


(laps := race.laps
    # calcualte pit stop duration
    .assign(pit_duration=lambda x: (x.PitOutTime.shift(-1) - x.PitInTime).dt.total_seconds())
    # the lap at which the pit stop was made
    .assign(pit_stop=lambda x: np.where(x.pit_duration > 0, x.LapNumber.astype(int), None))
    # the strategy after the pit stop
    .assign(strategy_after_pit=lambda x: np.where(x.shift(-1).Compound.isin(['SOFT']), 'SOFT', np.where(x.shift(-1).Compound.isin(['MEDIUM']), 'MEDIUM', np.where(x.shift(-1).Compound.isin(['HARD']), 'HARD', None))))
    # rename the compound column to strategy before the pit stop
    .rename(columns={'Compound': 'strategy_before_pit'})
    # filter only for laps with pit stops
    .query('pit_stop.notnull()')
    [
['Driver', 'DriverNumber', 'LapNumber', 'PitInTime', 'FreshTyre', 'TyreLife', 'TrackStatus', 'pit_duration', 'pit_stop', 'strategy_after_pit', 'strategy_before_pit']
    ]
)

laps

,Driver,DriverNumber,LapNumber,PitInTime,FreshTyre,TyreLife,TrackStatus,pit_duration,pit_stop,strategy_after_pit,strategy_before_pit
13,GAS,10,14.0,0 days 01:00:10.679000,True,14.0,1,31.053,14,None,WET
25,GAS,10,26.0,0 days 01:18:45.618000,True,12.0,1,32.291,26,MEDIUM,INTERMEDIATE
31,GAS,10,32.0,0 days 01:29:18.556000,True,6.0,45,1453.525,32,MEDIUM,MEDIUM
32,GAS,10,33.0,0 days 01:55:10.239000,False,6.0,51,56.077,33,MEDIUM,MEDIUM
90,PER,11,28.0,0 days 01:19:58.896000,True,28.0,1,44.676,28,MEDIUM,INTERMEDIATE
95,PER,11,33.0,0 days 01:29:11.663000,True,5.0,45,1581.172,33,SOFT,MEDIUM
153,ALO,14,28.0,0 days 01:21:18.812000,True,28.0,1,30.984,28,MEDIUM,INTERMEDIATE
157,ALO,14,32.0,0 days 01:28:37.450000,True,4.0,45,1488.331,32,MEDIUM,MEDIUM
158,ALO,14,33.0,0 days 01:55:05.161000,False,4.0,51,57.588,33,MEDIUM,MEDIUM
216,LEC,16,28.0,0 days 01:19:44.152000,True,28.0,1,30.958,28,MEDIUM,INTERMEDIATE
221,LEC,16,33.0,0 days 01:28:28.896000,True,5.0,45,1609.473,33,MEDIUM,MEDIUM
278,STR,18,27.0,0 days 01:19:16.421000,True,27.0,1,31.137,27,MEDIUM,INTERMEDIATE
283,STR,18,32.0,0 days 01:28:14.191000,True,5.0,45,1492.073,32,MEDIUM,MEDIUM
284,STR,18,33.0,0 days 01:54:37.429000,False,5.0,51,65.406,33,MEDIUM,MEDIUM
339,TSU,22,25.0,0 days 01:16:39.754000,True,25.0,1,30.696,25,MEDIUM,INTERMEDIATE
346,TSU,22,32.0,0 days 01:28:24.596000,True,7.0,45,1491.687,32,SOFT,MEDIUM
347,TSU,22,33.0,0 days 01:54:53.306000,True,1.0,51,63.320,33,SOFT,SOFT
404,RIC,3,27.0,0 days 01:18:57.991000,True,27.0,1,34.285,27,MEDIUM,INTERMEDIATE
410,RIC,3,33.0,0 days 01:29:26.051000,True,6.0,45,1575.137,33,SOFT,MEDIUM
441,OCO,31,1.0,0 days 00:35:16.950000,True,1.0,124,30.809,1,None,WET
467,OCO,31,27.0,0 days 01:19:42.796000,True,26.0,1,30.642,27,MEDIUM,INTERMEDIATE
471,OCO,31,31.0,0 days 01:26:23.677000,True,4.0,24,30.678,31,SOFT,MEDIUM
472,OCO,31,32.0,0 days 01:28:48.344000,False,3.0,45,1478.975,32,MEDIUM,SOFT
473,OCO,31,33.0,0 days 01:55:07.285000,False,5.0,51,56.736,33,MEDIUM,MEDIUM
530,VER,33,27.0,0 days 01:18:00.076000,True,27.0,1,30.543,27,MEDIUM,INTERMEDIATE
536,VER,33,33.0,0 days 01:28:12.328000,True,6.0,45,1621.405,33,MEDIUM,MEDIUM
594,NOR,4,28.0,0 days 01:20:11.399000,True,28.0,1,30.614,28,MEDIUM,INTERMEDIATE
599,NOR,4,33.0,0 days 01:29:06.624000,True,5.0,45,1584.936,33,SOFT,MEDIUM
657,HAM,44,28.0,0 days 01:19:27.715000,True,28.0,1,32.109,28,MEDIUM,INTERMEDIATE
660,HAM,44,31.0,0 days 01:25:31.176000,False,7.0,124,38.167,31,MEDIUM,MEDIUM
661,HAM,44,32.0,0 days 01:28:18.073000,True,1.0,45,1495.038,32,MEDIUM,MEDIUM
662,HAM,44,33.0,0 days 01:54:48.723000,False,1.0,51,65.841,33,MEDIUM,MEDIUM
697,MSC,47,5.0,0 days 00:45:12.244000,True,5.0,4,51.024,5,None,WET
713,MSC,47,21.0,0 days 01:11:24.543000,True,16.0,1,32.524,21,SOFT,INTERMEDIATE
723,MSC,47,31.0,0 days 01:28:20.908000,False,13.0,45,1521.337,31,MEDIUM,SOFT
724,MSC,47,32.0,0 days 01:55:17.270000,True,1.0,51,51.216,32,MEDIUM,MEDIUM
756,VET,5,3.0,0 days 00:40:10.348000,True,3.0,4,32.300,3,None,INTERMEDIATE
773,VET,5,20.0,0 days 01:09:11.436000,True,17.0,1,31.490,20,MEDIUM,INTERMEDIATE
775,VET,5,22.0,0 days 01:12:52.911000,True,2.0,1,39.795,22,MEDIUM,MEDIUM
785,VET,5,32.0,0 days 01:29:21.592000,False,12.0,45,1452.656,32,SOFT,MEDIUM
786,VET,5,33.0,0 days 01:55:15.581000,True,1.0,51,52.378,33,SOFT,SOFT
841,SAI,55,27.0,0 days 01:18:52.113000,True,27.0,1,30.852,27,MEDIUM,INTERMEDIATE
847,SAI,55,33.0,0 days 01:29:15.151000,True,6.0,45,1582.515,33,MEDIUM,MEDIUM
904,RUS,63,26.0,0 days 01:17:54.198000,True,26.0,1,29.988,26,MEDIUM,INTERMEDIATE
935,RAI,7,26.0,0 days 01:17:55.376000,True,26.0,1,30.324,26,MEDIUM,INTERMEDIATE
941,RAI,7,32.0,0 days 01:28:16.865000,True,6.0,45,1492.955,32,MEDIUM,MEDIUM
942,RAI,7,33.0,0 days 01:54:43.098000,False,6.0,51,63.170,33,MEDIUM,MEDIUM
1000,BOT,77,28.0,0 days 01:20:46.655000,True,28.0,1,30.148,28,MEDIUM,INTERMEDIATE
1015,MAZ,9,12.0,0 days 00:57:20.446000,True,12.0,12,31.111,12,None,WET
1026,MAZ,9,23.0,0 days 01:15:20.373000,True,11.0,1,31.487,23,SOFT,INTERMEDIATE
1034,MAZ,9,31.0,0 days 01:28:58.423000,False,11.0,45,1486.087,31,MEDIUM,SOFT
1035,MAZ,9,32.0,0 days 01:55:22.414000,True,1.0,51,49.738,32,MEDIUM,MEDIUM
1091,GIO,99,27.0,0 days 01:19:32.408000,True,27.0,1,32.282,27,MEDIUM,INTERMEDIATE
1096,GIO,99,32.0,0 days 01:28:26.634000,True,5.0,45,1496.441,32,MEDIUM,MEDIUM
1097,GIO,99,33.0,0 days 01:54:58.849000,False,5.0,51,60.173,33,MEDIUM,MEDIUM
1104,GIO,99,40.0,0 days 02:06:13.969000,False,13.0,1,29.687,40,MEDIUM,MEDIUM

In [15]:
# get the number of pit stops made for each driver
pit_stop_counts = laps.groupby('Driver')['pit_stop'].nunique().reset_index().rename(columns={'pit_stop': 'num_pit_stops'})
pit_stop_counts


laps_pit_stops = pd.merge(left=laps, right=pit_stop_counts, on='Driver', how='left')
laps_pit_stops

,Driver,DriverNumber,LapNumber,PitInTime,FreshTyre,TyreLife,TrackStatus,pit_duration,pit_stop,strategy_after_pit,strategy_before_pit,num_pit_stops
0,GAS,10,14.0,0 days 01:00:10.679000,True,14.0,1,31.053,14,None,WET,4
1,GAS,10,26.0,0 days 01:18:45.618000,True,12.0,1,32.291,26,MEDIUM,INTERMEDIATE,4
2,GAS,10,32.0,0 days 01:29:18.556000,True,6.0,45,1453.525,32,MEDIUM,MEDIUM,4
3,GAS,10,33.0,0 days 01:55:10.239000,False,6.0,51,56.077,33,MEDIUM,MEDIUM,4
4,PER,11,28.0,0 days 01:19:58.896000,True,28.0,1,44.676,28,MEDIUM,INTERMEDIATE,2
5,PER,11,33.0,0 days 01:29:11.663000,True,5.0,45,1581.172,33,SOFT,MEDIUM,2
6,ALO,14,28.0,0 days 01:21:18.812000,True,28.0,1,30.984,28,MEDIUM,INTERMEDIATE,3
7,ALO,14,32.0,0 days 01:28:37.450000,True,4.0,45,1488.331,32,MEDIUM,MEDIUM,3
8,ALO,14,33.0,0 days 01:55:05.161000,False,4.0,51,57.588,33,MEDIUM,MEDIUM,3
9,LEC,16,28.0,0 days 01:19:44.152000,True,28.0,1,30.958,28,MEDIUM,INTERMEDIATE,2
10,LEC,16,33.0,0 days 01:28:28.896000,True,5.0,45,1609.473,33,MEDIUM,MEDIUM,2
11,STR,18,27.0,0 days 01:19:16.421000,True,27.0,1,31.137,27,MEDIUM,INTERMEDIATE,3
12,STR,18,32.0,0 days 01:28:14.191000,True,5.0,45,1492.073,32,MEDIUM,MEDIUM,3
13,STR,18,33.0,0 days 01:54:37.429000,False,5.0,51,65.406,33,MEDIUM,MEDIUM,3
14,TSU,22,25.0,0 days 01:16:39.754000,True,25.0,1,30.696,25,MEDIUM,INTERMEDIATE,3
15,TSU,22,32.0,0 days 01:28:24.596000,True,7.0,45,1491.687,32,SOFT,MEDIUM,3
16,TSU,22,33.0,0 days 01:54:53.306000,True,1.0,51,63.320,33,SOFT,SOFT,3
17,RIC,3,27.0,0 days 01:18:57.991000,True,27.0,1,34.285,27,MEDIUM,INTERMEDIATE,2
18,RIC,3,33.0,0 days 01:29:26.051000,True,6.0,45,1575.137,33,SOFT,MEDIUM,2
19,OCO,31,1.0,0 days 00:35:16.950000,True,1.0,124,30.809,1,None,WET,5
20,OCO,31,27.0,0 days 01:19:42.796000,True,26.0,1,30.642,27,MEDIUM,INTERMEDIATE,5
21,OCO,31,31.0,0 days 01:26:23.677000,True,4.0,24,30.678,31,SOFT,MEDIUM,5
22,OCO,31,32.0,0 days 01:28:48.344000,False,3.0,45,1478.975,32,MEDIUM,SOFT,5
23,OCO,31,33.0,0 days 01:55:07.285000,False,5.0,51,56.736,33,MEDIUM,MEDIUM,5
24,VER,33,27.0,0 days 01:18:00.076000,True,27.0,1,30.543,27,MEDIUM,INTERMEDIATE,2
25,VER,33,33.0,0 days 01:28:12.328000,True,6.0,45,1621.405,33,MEDIUM,MEDIUM,2
26,NOR,4,28.0,0 days 01:20:11.399000,True,28.0,1,30.614,28,MEDIUM,INTERMEDIATE,2
27,NOR,4,33.0,0 days 01:29:06.624000,True,5.0,45,1584.936,33,SOFT,MEDIUM,2
28,HAM,44,28.0,0 days 01:19:27.715000,True,28.0,1,32.109,28,MEDIUM,INTERMEDIATE,4
29,HAM,44,31.0,0 days 01:25:31.176000,False,7.0,124,38.167,31,MEDIUM,MEDIUM,4
30,HAM,44,32.0,0 days 01:28:18.073000,True,1.0,45,1495.038,32,MEDIUM,MEDIUM,4
31,HAM,44,33.0,0 days 01:54:48.723000,False,1.0,51,65.841,33,MEDIUM,MEDIUM,4
32,MSC,47,5.0,0 days 00:45:12.244000,True,5.0,4,51.024,5,None,WET,4
33,MSC,47,21.0,0 days 01:11:24.543000,True,16.0,1,32.524,21,SOFT,INTERMEDIATE,4
34,MSC,47,31.0,0 days 01:28:20.908000,False,13.0,45,1521.337,31,MEDIUM,SOFT,4
35,MSC,47,32.0,0 days 01:55:17.270000,True,1.0,51,51.216,32,MEDIUM,MEDIUM,4
36,VET,5,3.0,0 days 00:40:10.348000,True,3.0,4,32.300,3,None,INTERMEDIATE,5
37,VET,5,20.0,0 days 01:09:11.436000,True,17.0,1,31.490,20,MEDIUM,INTERMEDIATE,5
38,VET,5,22.0,0 days 01:12:52.911000,True,2.0,1,39.795,22,MEDIUM,MEDIUM,5
39,VET,5,32.0,0 days 01:29:21.592000,False,12.0,45,1452.656,32,SOFT,MEDIUM,5
40,VET,5,33.0,0 days 01:55:15.581000,True,1.0,51,52.378,33,SOFT,SOFT,5
41,SAI,55,27.0,0 days 01:18:52.113000,True,27.0,1,30.852,27,MEDIUM,INTERMEDIATE,2
42,SAI,55,33.0,0 days 01:29:15.151000,True,6.0,45,1582.515,33,MEDIUM,MEDIUM,2
43,RUS,63,26.0,0 days 01:17:54.198000,True,26.0,1,29.988,26,MEDIUM,INTERMEDIATE,1
44,RAI,7,26.0,0 days 01:17:55.376000,True,26.0,1,30.324,26,MEDIUM,INTERMEDIATE,3
45,RAI,7,32.0,0 days 01:28:16.865000,True,6.0,45,1492.955,32,MEDIUM,MEDIUM,3
46,RAI,7,33.0,0 days 01:54:43.098000,False,6.0,51,63.170,33,MEDIUM,MEDIUM,3
47,BOT,77,28.0,0 days 01:20:46.655000,True,28.0,1,30.148,28,MEDIUM,INTERMEDIATE,1
48,MAZ,9,12.0,0 days 00:57:20.446000,True,12.0,12,31.111,12,None,WET,4
49,MAZ,9,23.0,0 days 01:15:20.373000,True,11.0,1,31.487,23,SOFT,INTERMEDIATE,4
50,MAZ,9,31.0,0 days 01:28:58.423000,False,11.0,45,1486.087,31,MEDIUM,SOFT,4
51,MAZ,9,32.0,0 days 01:55:22.414000,True,1.0,51,49.738,32,MEDIUM,MEDIUM,4
52,GIO,99,27.0,0 days 01:19:32.408000,True,27.0,1,32.282,27,MEDIUM,INTERMEDIATE,4
53,GIO,99,32.0,0 days 01:28:26.634000,True,5.0,45,1496.441,32,MEDIUM,MEDIUM,4
54,GIO,99,33.0,0 days 01:54:58.849000,False,5.0,51,60.173,33,MEDIUM,MEDIUM,4
55,GIO,99,40.0,0 days 02:06:13.969000,False,13.0,1,29.687,40,MEDIUM,MEDIUM,4

In [16]:
# Flatten/pivot the above such that we have one row per driver, and columns for each pit stop (lap number, duration, strategy before and after the pit stop)
laps_pit_stops['stop_num'] = laps_pit_stops.groupby('Driver').cumcount() + 1
per_stop_cols = {
        "LapNumber": "lap",
        "pit_duration": "duration",
        "PitInTime": "intime",
        "FreshTyre": "fresh",
        "strategy_before_pit": "tyre_before",
        "strategy_after_pit": "tyre_after",
    }

pivoted = laps_pit_stops.groupby('Driver').first()[["DriverNumber", "num_pit_stops"]].reset_index()


for src_col, label in per_stop_cols.items():
    stop_pivot = (
            laps_pit_stops.pivot_table(index='Driver', columns="stop_num", values=src_col, aggfunc="first")
        )
    stop_pivot.columns = [f"pit_{int(n)}_{label}" for n in stop_pivot.columns]
    pivoted = pivoted.merge(stop_pivot.reset_index(), on='Driver', how="left")


laps_pit_stops_flat = pivoted.sort_values('DriverNumber').reset_index(drop=True)
laps_pit_stops_flat

,Driver,DriverNumber,num_pit_stops,pit_1_lap,pit_2_lap,pit_3_lap,pit_4_lap,pit_5_lap,pit_1_duration,pit_2_duration,pit_3_duration,pit_4_duration,pit_5_duration,pit_1_intime,pit_2_intime,pit_3_intime,pit_4_intime,pit_5_intime,pit_1_fresh,pit_2_fresh,pit_3_fresh,pit_4_fresh,pit_5_fresh,pit_1_tyre_before,pit_2_tyre_before,pit_3_tyre_before,pit_4_tyre_before,pit_5_tyre_before,pit_1_tyre_after,pit_2_tyre_after,pit_3_tyre_after,pit_4_tyre_after,pit_5_tyre_after
0,GAS,10,4,14.0,26.0,32.0,33.0,NaN,31.053,32.291,1453.525,56.077,NaN,0 days 01:00:10.679000,0 days 01:18:45.618000,0 days 01:29:18.556000,0 days 01:55:10.239000,NaT,True,True,True,False,NaN,WET,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN
1,PER,11,2,28.0,33.0,NaN,NaN,NaN,44.676,1581.172,NaN,NaN,NaN,0 days 01:19:58.896000,0 days 01:29:11.663000,NaT,NaT,NaT,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN
2,ALO,14,3,28.0,32.0,33.0,NaN,NaN,30.984,1488.331,57.588,NaN,NaN,0 days 01:21:18.812000,0 days 01:28:37.450000,0 days 01:55:05.161000,NaT,NaT,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN
3,LEC,16,2,28.0,33.0,NaN,NaN,NaN,30.958,1609.473,NaN,NaN,NaN,0 days 01:19:44.152000,0 days 01:28:28.896000,NaT,NaT,NaT,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN
4,STR,18,3,27.0,32.0,33.0,NaN,NaN,31.137,1492.073,65.406,NaN,NaN,0 days 01:19:16.421000,0 days 01:28:14.191000,0 days 01:54:37.429000,NaT,NaT,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN
5,TSU,22,3,25.0,32.0,33.0,NaN,NaN,30.696,1491.687,63.320,NaN,NaN,0 days 01:16:39.754000,0 days 01:28:24.596000,0 days 01:54:53.306000,NaT,NaT,True,True,True,NaN,NaN,INTERMEDIATE,MEDIUM,SOFT,NaN,NaN,MEDIUM,SOFT,SOFT,NaN,NaN
6,RIC,3,2,27.0,33.0,NaN,NaN,NaN,34.285,1575.137,NaN,NaN,NaN,0 days 01:18:57.991000,0 days 01:29:26.051000,NaT,NaT,NaT,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN
7,OCO,31,5,1.0,27.0,31.0,32.0,33.0,30.809,30.642,30.678,1478.975,56.736,0 days 00:35:16.950000,0 days 01:19:42.796000,0 days 01:26:23.677000,0 days 01:28:48.344000,0 days 01:55:07.285000,True,True,True,False,False,WET,INTERMEDIATE,MEDIUM,SOFT,MEDIUM,NaN,MEDIUM,SOFT,MEDIUM,MEDIUM
8,VER,33,2,27.0,33.0,NaN,NaN,NaN,30.543,1621.405,NaN,NaN,NaN,0 days 01:18:00.076000,0 days 01:28:12.328000,NaT,NaT,NaT,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN
9,NOR,4,2,28.0,33.0,NaN,NaN,NaN,30.614,1584.936,NaN,NaN,NaN,0 days 01:20:11.399000,0 days 01:29:06.624000,NaT,NaT,NaT,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN
10,HAM,44,4,28.0,31.0,32.0,33.0,NaN,32.109,38.167,1495.038,65.841,NaN,0 days 01:19:27.715000,0 days 01:25:31.176000,0 days 01:28:18.073000,0 days 01:54:48.723000,NaT,True,False,True,False,NaN,INTERMEDIATE,MEDIUM,MEDIUM,MEDIUM,NaN,MEDIUM,MEDIUM,MEDIUM,MEDIUM,NaN
11,MSC,47,4,5.0,21.0,31.0,32.0,NaN,51.024,32.524,1521.337,51.216,NaN,0 days 00:45:12.244000,0 days 01:11:24.543000,0 days 01:28:20.908000,0 days 01:55:17.270000,NaT,True,True,False,True,NaN,WET,INTERMEDIATE,SOFT,MEDIUM,NaN,NaN,SOFT,MEDIUM,MEDIUM,NaN
12,VET,5,5,3.0,20.0,22.0,32.0,33.0,32.300,31.490,39.795,1452.656,52.378,0 days 00:40:10.348000,0 days 01:09:11.436000,0 days 01:12:52.911000,0 days 01:29:21.592000,0 days 01:55:15.581000,True,True,True,False,True,INTERMEDIATE,INTERMEDIATE,MEDIUM,MEDIUM,SOFT,NaN,MEDIUM,MEDIUM,SOFT,SOFT
13,SAI,55,2,27.0,33.0,NaN,NaN,NaN,30.852,1582.515,NaN,NaN,NaN,0 days 01:18:52.113000,0 days 01:29:15.151000,NaT,NaT,NaT,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN
14,RUS,63,1,26.0,NaN,NaN,NaN,NaN,29.988,NaN,NaN,NaN,NaN,0 days 01:17:54.198000,NaT,NaT,NaT,NaT,True,NaN,NaN,NaN,NaN,INTERMEDIATE,NaN,NaN,NaN,NaN,MEDIUM,NaN,NaN,NaN,NaN
15,RAI,7,3,26.0,32.0,33.0,NaN,NaN,30.324,1492.955,63.170,NaN,NaN,0 days 01:17:55.376000,0 days 01:28:16.865000,0 days 01:54:43.098000,NaT,NaT,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN
16,BOT,77,1,28.0,NaN,NaN,NaN,NaN,30.148,NaN,NaN,NaN,NaN,0 days 01:20:46.655000,NaT,NaT,NaT,NaT,True,NaN,NaN,NaN,NaN,INTERMEDIATE,NaN,NaN,NaN,NaN,MEDIUM,NaN,NaN,NaN,NaN
17,MAZ,9,4,12.0,23.0,31.0,32.0,NaN,31.111,31.487,1486.087,49.738,NaN,0 days 00:57:20.446000,0 days 01:15:20.373000,0 days 01:28:58.423000,0 days 01:55:22.414000,NaT,True,True,False,True,NaN,WET,INTERMEDIATE,SOFT,MEDIUM,NaN,NaN,SOFT,MEDIUM,MEDIUM,NaN
18,GIO,99,4,27.0,32.0,33.0,40.0,NaN,32.282,1496.441,60.173,29.687,NaN,0 days 01:19:32.408000,0 days 01:28:26.634000,0 days 01:54:58.849000,0 days 02:06:13.969000,NaT,True,True,False,False,NaN,INTERMEDIATE,MEDIUM,MEDIUM,MEDIUM,NaN,MEDIUM,MEDIUM,MEDIUM,MEDIUM,NaN

In [17]:
for col, dtype in laps_pit_stops_flat.dtypes.items():
    if dtype == 'timedelta64[ns]':
        laps_pit_stops_flat[col] = laps_pit_stops_flat[col].dt.total_seconds().astype(float)

laps_pit_stops_flat

,Driver,DriverNumber,num_pit_stops,pit_1_lap,pit_2_lap,pit_3_lap,pit_4_lap,pit_5_lap,pit_1_duration,pit_2_duration,pit_3_duration,pit_4_duration,pit_5_duration,pit_1_intime,pit_2_intime,pit_3_intime,pit_4_intime,pit_5_intime,pit_1_fresh,pit_2_fresh,pit_3_fresh,pit_4_fresh,pit_5_fresh,pit_1_tyre_before,pit_2_tyre_before,pit_3_tyre_before,pit_4_tyre_before,pit_5_tyre_before,pit_1_tyre_after,pit_2_tyre_after,pit_3_tyre_after,pit_4_tyre_after,pit_5_tyre_after
0,GAS,10,4,14.0,26.0,32.0,33.0,NaN,31.053,32.291,1453.525,56.077,NaN,3610.679,4725.618,5358.556,6910.239,NaN,True,True,True,False,NaN,WET,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN
1,PER,11,2,28.0,33.0,NaN,NaN,NaN,44.676,1581.172,NaN,NaN,NaN,4798.896,5351.663,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN
2,ALO,14,3,28.0,32.0,33.0,NaN,NaN,30.984,1488.331,57.588,NaN,NaN,4878.812,5317.450,6905.161,NaN,NaN,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN
3,LEC,16,2,28.0,33.0,NaN,NaN,NaN,30.958,1609.473,NaN,NaN,NaN,4784.152,5308.896,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN
4,STR,18,3,27.0,32.0,33.0,NaN,NaN,31.137,1492.073,65.406,NaN,NaN,4756.421,5294.191,6877.429,NaN,NaN,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN
5,TSU,22,3,25.0,32.0,33.0,NaN,NaN,30.696,1491.687,63.320,NaN,NaN,4599.754,5304.596,6893.306,NaN,NaN,True,True,True,NaN,NaN,INTERMEDIATE,MEDIUM,SOFT,NaN,NaN,MEDIUM,SOFT,SOFT,NaN,NaN
6,RIC,3,2,27.0,33.0,NaN,NaN,NaN,34.285,1575.137,NaN,NaN,NaN,4737.991,5366.051,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN
7,OCO,31,5,1.0,27.0,31.0,32.0,33.0,30.809,30.642,30.678,1478.975,56.736,2116.950,4782.796,5183.677,5328.344,6907.285,True,True,True,False,False,WET,INTERMEDIATE,MEDIUM,SOFT,MEDIUM,NaN,MEDIUM,SOFT,MEDIUM,MEDIUM
8,VER,33,2,27.0,33.0,NaN,NaN,NaN,30.543,1621.405,NaN,NaN,NaN,4680.076,5292.328,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN
9,NOR,4,2,28.0,33.0,NaN,NaN,NaN,30.614,1584.936,NaN,NaN,NaN,4811.399,5346.624,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN
10,HAM,44,4,28.0,31.0,32.0,33.0,NaN,32.109,38.167,1495.038,65.841,NaN,4767.715,5131.176,5298.073,6888.723,NaN,True,False,True,False,NaN,INTERMEDIATE,MEDIUM,MEDIUM,MEDIUM,NaN,MEDIUM,MEDIUM,MEDIUM,MEDIUM,NaN
11,MSC,47,4,5.0,21.0,31.0,32.0,NaN,51.024,32.524,1521.337,51.216,NaN,2712.244,4284.543,5300.908,6917.270,NaN,True,True,False,True,NaN,WET,INTERMEDIATE,SOFT,MEDIUM,NaN,NaN,SOFT,MEDIUM,MEDIUM,NaN
12,VET,5,5,3.0,20.0,22.0,32.0,33.0,32.300,31.490,39.795,1452.656,52.378,2410.348,4151.436,4372.911,5361.592,6915.581,True,True,True,False,True,INTERMEDIATE,INTERMEDIATE,MEDIUM,MEDIUM,SOFT,NaN,MEDIUM,MEDIUM,SOFT,SOFT
13,SAI,55,2,27.0,33.0,NaN,NaN,NaN,30.852,1582.515,NaN,NaN,NaN,4732.113,5355.151,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN
14,RUS,63,1,26.0,NaN,NaN,NaN,NaN,29.988,NaN,NaN,NaN,NaN,4674.198,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,INTERMEDIATE,NaN,NaN,NaN,NaN,MEDIUM,NaN,NaN,NaN,NaN
15,RAI,7,3,26.0,32.0,33.0,NaN,NaN,30.324,1492.955,63.170,NaN,NaN,4675.376,5296.865,6883.098,NaN,NaN,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN
16,BOT,77,1,28.0,NaN,NaN,NaN,NaN,30.148,NaN,NaN,NaN,NaN,4846.655,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,INTERMEDIATE,NaN,NaN,NaN,NaN,MEDIUM,NaN,NaN,NaN,NaN
17,MAZ,9,4,12.0,23.0,31.0,32.0,NaN,31.111,31.487,1486.087,49.738,NaN,3440.446,4520.373,5338.423,6922.414,NaN,True,True,False,True,NaN,WET,INTERMEDIATE,SOFT,MEDIUM,NaN,NaN,SOFT,MEDIUM,MEDIUM,NaN
18,GIO,99,4,27.0,32.0,33.0,40.0,NaN,32.282,1496.441,60.173,29.687,NaN,4772.408,5306.634,6898.849,7573.969,NaN,True,True,False,False,NaN,INTERMEDIATE,MEDIUM,MEDIUM,MEDIUM,NaN,MEDIUM,MEDIUM,MEDIUM,MEDIUM,NaN

## Weather

In [27]:
laps_pit_stops_weather = pd.merge_asof(left=laps_pit_stops_flat.sort_values('pit_1_intime'), right=weather_data, left_on='pit_1_intime', right_on='Time', direction='backward')

In [31]:
laps_pit_stops_weather

,Driver,DriverNumber,num_pit_stops,pit_1_lap,pit_2_lap,pit_3_lap,pit_4_lap,pit_5_lap,pit_1_duration,pit_2_duration,pit_3_duration,pit_4_duration,pit_5_duration,pit_1_intime,pit_2_intime,pit_3_intime,pit_4_intime,pit_5_intime,pit_1_fresh,pit_2_fresh,pit_3_fresh,pit_4_fresh,pit_5_fresh,pit_1_tyre_before,pit_2_tyre_before,pit_3_tyre_before,pit_4_tyre_before,pit_5_tyre_before,pit_1_tyre_after,pit_2_tyre_after,pit_3_tyre_after,pit_4_tyre_after,pit_5_tyre_after,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed,rain_start,rain_stop,rain_start_time,rain_stop_time
0,OCO,31,5,1.0,27.0,31.0,32.0,33.0,30.809,30.642,30.678,1478.975,56.736,2116.950,4782.796,5183.677,5328.344,6907.285,True,True,True,False,False,WET,INTERMEDIATE,MEDIUM,SOFT,MEDIUM,NaN,MEDIUM,SOFT,MEDIUM,MEDIUM,2081.415,9.6,75.4,1011.5,True,17.3,203,0.2,False,False,NaN,NaN
1,VET,5,5,3.0,20.0,22.0,32.0,33.0,32.300,31.490,39.795,1452.656,52.378,2410.348,4151.436,4372.911,5361.592,6915.581,True,True,True,False,True,INTERMEDIATE,INTERMEDIATE,MEDIUM,MEDIUM,SOFT,NaN,MEDIUM,MEDIUM,SOFT,SOFT,2381.413,9.6,76.8,1011.5,True,16.5,91,0.3,False,False,NaN,NaN
2,MSC,47,4,5.0,21.0,31.0,32.0,NaN,51.024,32.524,1521.337,51.216,NaN,2712.244,4284.543,5300.908,6917.270,NaN,True,True,False,True,NaN,WET,INTERMEDIATE,SOFT,MEDIUM,NaN,NaN,SOFT,MEDIUM,MEDIUM,NaN,2681.414,9.7,74.7,1011.5,True,16.3,95,0.2,False,False,NaN,NaN
3,MAZ,9,4,12.0,23.0,31.0,32.0,NaN,31.111,31.487,1486.087,49.738,NaN,3440.446,4520.373,5338.423,6922.414,NaN,True,True,False,True,NaN,WET,INTERMEDIATE,SOFT,MEDIUM,NaN,NaN,SOFT,MEDIUM,MEDIUM,NaN,3401.415,10.2,68.2,1011.4,True,14.9,91,0.9,False,False,NaN,NaN
4,GAS,10,4,14.0,26.0,32.0,33.0,NaN,31.053,32.291,1453.525,56.077,NaN,3610.679,4725.618,5358.556,6910.239,NaN,True,True,True,False,NaN,WET,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,3581.414,10.3,68.5,1011.3,True,14.3,82,0.8,False,False,NaN,NaN
5,TSU,22,3,25.0,32.0,33.0,NaN,NaN,30.696,1491.687,63.320,NaN,NaN,4599.754,5304.596,6893.306,NaN,NaN,True,True,True,NaN,NaN,INTERMEDIATE,MEDIUM,SOFT,NaN,NaN,MEDIUM,SOFT,SOFT,NaN,NaN,4541.409,10.9,68.6,1011.3,False,14.7,92,1.0,False,False,NaN,3761.415
6,RUS,63,1,26.0,NaN,NaN,NaN,NaN,29.988,NaN,NaN,NaN,NaN,4674.198,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,INTERMEDIATE,NaN,NaN,NaN,NaN,MEDIUM,NaN,NaN,NaN,NaN,4661.416,11.0,67.7,1011.3,False,15.0,95,1.0,False,False,NaN,3761.415
7,RAI,7,3,26.0,32.0,33.0,NaN,NaN,30.324,1492.955,63.170,NaN,NaN,4675.376,5296.865,6883.098,NaN,NaN,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN,4661.416,11.0,67.7,1011.3,False,15.0,95,1.0,False,False,NaN,3761.415
8,VER,33,2,27.0,33.0,NaN,NaN,NaN,30.543,1621.405,NaN,NaN,NaN,4680.076,5292.328,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN,4661.416,11.0,67.7,1011.3,False,15.0,95,1.0,False,False,NaN,3761.415
9,SAI,55,2,27.0,33.0,NaN,NaN,NaN,30.852,1582.515,NaN,NaN,NaN,4732.113,5355.151,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN,4721.412,11.1,67.6,1011.2,False,15.2,102,1.0,False,False,NaN,3761.415
10,RIC,3,2,27.0,33.0,NaN,NaN,NaN,34.285,1575.137,NaN,NaN,NaN,4737.991,5366.051,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN,4721.412,11.1,67.6,1011.2,False,15.2,102,1.0,False,False,NaN,3761.415
11,STR,18,3,27.0,32.0,33.0,NaN,NaN,31.137,1492.073,65.406,NaN,NaN,4756.421,5294.191,6877.429,NaN,NaN,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN,4721.412,11.1,67.6,1011.2,False,15.2,102,1.0,False,False,NaN,3761.415
12,HAM,44,4,28.0,31.0,32.0,33.0,NaN,32.109,38.167,1495.038,65.841,NaN,4767.715,5131.176,5298.073,6888.723,NaN,True,False,True,False,NaN,INTERMEDIATE,MEDIUM,MEDIUM,MEDIUM,NaN,MEDIUM,MEDIUM,MEDIUM,MEDIUM,NaN,4721.412,11.1,67.6,1011.2,False,15.2,102,1.0,False,False,NaN,3761.415
13,GIO,99,4,27.0,32.0,33.0,40.0,NaN,32.282,1496.441,60.173,29.687,NaN,4772.408,5306.634,6898.849,7573.969,NaN,True,True,False,False,NaN,INTERMEDIATE,MEDIUM,MEDIUM,MEDIUM,NaN,MEDIUM,MEDIUM,MEDIUM,MEDIUM,NaN,4721.412,11.1,67.6,1011.2,False,15.2,102,1.0,False,False,NaN,3761.415
14,LEC,16,2,28.0,33.0,NaN,NaN,NaN,30.958,1609.473,NaN,NaN,NaN,4784.152,5308.896,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,MEDIUM,NaN,NaN,NaN,4781.413,11.1,67.3,1011.1,False,15.3,97,1.1,False,False,NaN,3761.415
15,PER,11,2,28.0,33.0,NaN,NaN,NaN,44.676,1581.172,NaN,NaN,NaN,4798.896,5351.663,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN,4781.413,11.1,67.3,1011.1,False,15.3,97,1.1,False,False,NaN,3761.415
16,NOR,4,2,28.0,33.0,NaN,NaN,NaN,30.614,1584.936,NaN,NaN,NaN,4811.399,5346.624,NaN,NaN,NaN,True,True,NaN,NaN,NaN,INTERMEDIATE,MEDIUM,NaN,NaN,NaN,MEDIUM,SOFT,NaN,NaN,NaN,4781.413,11.1,67.3,1011.1,False,15.3,97,1.1,False,False,NaN,3761.415
17,BOT,77,1,28.0,NaN,NaN,NaN,NaN,30.148,NaN,NaN,NaN,NaN,4846.655,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,INTERMEDIATE,NaN,NaN,NaN,NaN,MEDIUM,NaN,NaN,NaN,NaN,4841.419,11.1,65.9,1011.2,False,15.4,88,1.1,False,False,NaN,3761.415
18,ALO,14,3,28.0,32.0,33.0,NaN,NaN,30.984,1488.331,57.588,NaN,NaN,4878.812,5317.450,6905.161,NaN,NaN,True,True,False,NaN,NaN,INTERMEDIATE,MEDIUM,MEDIUM,NaN,NaN,MEDIUM,MEDIUM,MEDIUM,NaN,NaN,4841.419,11.1,65.9,1011.2,False,15.4,88,1.1,False,False,NaN,3761.415

## Putting it Together

In [7]:
def transform_weather(weather_data: pd.DataFrame):
    # pass in race.weather_data
    weather_data['rain_start'] = (weather_data['Rainfall'] == True) & (weather_data['Rainfall'].shift(1) == False)
    weather_data['rain_stop'] = (weather_data['Rainfall'].shift(1) == True) & (weather_data['Rainfall'] == False)
    weather_data['rain_start_time'] = weather_data['Time'].where(weather_data['rain_start']) 
    weather_data['rain_stop_time'] = weather_data['Time'].where(weather_data['rain_stop'])

    weather_data['rain_start_time'] = weather_data['rain_start_time'].dt.total_seconds().astype(float)
    weather_data['rain_stop_time'] = weather_data['rain_stop_time'].dt.total_seconds().astype(float)

    weather_data['rain_start_time'] = weather_data['rain_start_time'].ffill()
    weather_data['rain_stop_time'] = weather_data['rain_stop_time'].ffill()

    weather_data['Time'] = weather_data['Time'].dt.total_seconds().astype(float)


    weather_data['max_temp'] = weather_data['TrackTemp'].max()
    weather_data['min_temp'] = weather_data['TrackTemp'].min()
    weather_data['avg_temp'] = weather_data['TrackTemp'].mean()
    weather_data['std_temp'] = weather_data['TrackTemp'].std()

    return weather_data

In [8]:
def transform_circuit_info(circuit_info: pd.DataFrame):
    corners = circuit_info.corners[['Angle', 'Distance']]
    return corners

In [10]:
def transform_start_end_positions(results: pd.DataFrame):
    return pd.concat([results['Position'],results['GridPosition']], axis=1).rename(columns={'Position': 'target', 'GridPosition': 'starting_position'}).astype({'starting_position': 'int', 'target': 'int'})

In [11]:
def transform_laps_pit_stops(laps: pd.DataFrame):
    laps = (
        laps[['Driver', 'DriverNumber', 'LapNumber', 'PitInTime', 'PitOutTime', 'FreshTyre', 'TyreLife', 'Compound', 'TrackStatus']]
        # calcualte pit stop duration
        .assign(
            pit_duration=lambda x: (
                x.PitOutTime.shift(-1) - x.PitInTime
            ).dt.total_seconds()
        )
        # the lap at which the pit stop was made
        .assign(
            pit_stop=lambda x: np.where(
                x.pit_duration > 0, x.LapNumber.astype(int), None
            )
        )
        # the strategy after the pit stop
        .assign(
            strategy_after_pit=lambda x: np.where(
                x.shift(-1).Compound.isin(["SOFT"]),
                "SOFT",
                np.where(
                    x.shift(-1).Compound.isin(["MEDIUM"]),
                    "MEDIUM",
                    np.where(x.shift(-1).Compound.isin(["HARD"]), "HARD", None),
                ),
            )
        )
        # rename the compound column to strategy before the pit stop
        .rename(columns={"Compound": "strategy_before_pit"})
        # filter only for laps with pit stops
        .query("pit_stop.notnull()")[
            [
                "Driver",
                "DriverNumber",
                "LapNumber",
                "PitInTime",
                "FreshTyre",
                "TyreLife",
                "TrackStatus",
                "pit_duration",
                "pit_stop",
                "strategy_after_pit",
                "strategy_before_pit",
            ]
        ]
    )

    pit_stop_counts = laps.groupby('Driver')['pit_stop'].nunique().reset_index().rename(columns={'pit_stop': 'num_pit_stops'})

    laps_pit_stops = pd.merge(left=laps, right=pit_stop_counts, on='Driver', how='left')

    # Flatten/pivot the above such that we have one row per driver, and columns for each pit stop (lap number, duration, strategy before and after the pit stop)
    laps_pit_stops['stop_num'] = laps_pit_stops.groupby('Driver').cumcount() + 1
    per_stop_cols = {
            "LapNumber": "lap",
            "pit_duration": "duration",
            "PitInTime": "intime",
            "FreshTyre": "fresh",
            "strategy_before_pit": "tyre_before",
            "strategy_after_pit": "tyre_after",
        }

    pivoted = laps_pit_stops.groupby('Driver').first()[["DriverNumber", "num_pit_stops"]].reset_index()


    for src_col, label in per_stop_cols.items():
        stop_pivot = (
                laps_pit_stops.pivot_table(index='Driver', columns="stop_num", values=src_col, aggfunc="first")
            )
        stop_pivot.columns = [f"pit_{int(n)}_{label}" for n in stop_pivot.columns]
        pivoted = pivoted.merge(stop_pivot.reset_index(), on='Driver', how="left")


    laps_pit_stops_flat = pivoted.sort_values('DriverNumber').reset_index(drop=True)
    for col, dtype in laps_pit_stops_flat.dtypes.items():
        if dtype == 'timedelta64[ns]':
            laps_pit_stops_flat[col] = laps_pit_stops_flat[col].dt.total_seconds().astype(float)


    return laps_pit_stops_flat

In [ ]:
def merge_laps_with_weather(laps, weather_data):
    return pd.merge_asof(
        left=laps.sort_values('pit_1_intime'),
        right=weather_data,
        left_on='pit_1_intime',
        right_on='Time',
        direction='backward'
    )

In [18]:
for year in [2021]:
    countries = list(fastf1.get_event_schedule(year).Location.unique())
    for country in ['Bahrain']:#countries:
        race = fastf1.get_session(year, country, "R")
        race.load()
        weather_data = transform_weather(race.weather_data)
        circuit_info = transform_circuit_info(race.get_circuit_info())
        start_end_positions = transform_start_end_positions(race.results)
        laps_pit_stops = transform_laps_pit_stops(race.laps)  
        df = merge_laps_with_weather(laps_pit_stops, weather_data)

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.2]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Driver 44 completed the race distance 00:00.067000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '33', '77', '4', '11', '16', '3', '55', '22', '18', '7', '99', '31', '63', '5', '47', '10', '6', '14', '9']

NameError: name 'np' is not defined